spring:
  application:
    name: closet

  datasource:
    url: jdbc:postgresql://localhost:5432/closet
    driver-class-name: org.postgresql.Driver
    username: closet-user
    password: closet_1234

  jpa:
    hibernate:
      ddl-auto: update   # (dev환경이면 update OK / prod는 validate 권장)
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  sql:
    init:
      mode: always

closet:
  storage:
    type: ${STORAGE_TYPE:local}
    local:
      root-path: ${STORAGE_LOCAL_ROOT_PATH:storage}
  admin:
    username: ${ADMIN_USERNAME:admin}
    email: ${ADMIN_EMAIL:admin@admin.com}
    password: ${ADMIN_PASSWORD:admin123}
  weather:
    api:
      base-url: http://apis.data.go.kr/1360000/VilageFcstInfoService_2.0
      service-key: yU4xHTnvzWjv45heJROSYL9Xn6g3hp0Evb9KXevF5Vdsw6qig1I692t1RNu3G42wU2LNTS+QK/lyUC/UgVPcHw==
      timeout: 10000
      data-type: JSON

security:
  jwt:
    issuer: closet
    secret: ${JWT_SECRET:376352270f35f8070b7a7e2ae299ca43}
    access-token-validity-seconds: 3600 # 1시간
    refresh-token-validity-seconds: 1204000 # 14일

logging:
  level:
    root: info
    org.hibernate.sql: info
    org.hibernate.type: info