spring:
  application:
    name: closet

  datasource:
    url: jdbc:postgresql://localhost:5432/closet
    driver-class-name: org.postgresql.Driver
    username: closet-user
    password: closet_1234

  jpa:
    hibernate:
      ddl-auto: update   # (dev환경이면 update OK / prod는 validate 권장)
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

closet:
  storage:
    type: ${STORAGE_TYPE:local}
    local:
      root-path: ${STORAGE_LOCAL_ROOT_PATH:storage}