spring:
  profiles:
    include: kafka # 혹시 문제 생긴다면 지우시면 됩니다.
  application:
    name: closet

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SMTP_USERNAME:example@example.com}
    password: ${SMTP_PASSWORD:dummypassword}
    properties:
      mail.smtp.debug: true
      mail.smtp.connection.timeout: 1000 #1초
      mail.smtp.starttls.enable: true
      mail.smtp.auth: true

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/closet}
    driver-class-name: org.postgresql.Driver
    username: ${DATABASE_USERNAME:closet-user}
    password: ${DATABASE_PASSWORD:closet_1234}

  cache:
    # type: caffeine
    type: redis
    cache-names:
      - users # 추가 해주시면 됩니다. (yml 리스트 형식으로)
      - userProfile
    redis:
      enable-statistics: true
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

  jpa:
    hibernate:
      ddl-auto: update   # (dev환경이면 update OK / prod는 validate 권장)
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  security:
    jwt:
      issuer: closet
      secret: ${JWT_SECRET:376352270f35f8070b7a7e2ae299ca43}
      access-token-validity-seconds: 3600 # 1시간
      refresh-token-validity-seconds: 1204000 # 14일
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID:dummy}
            client-secret: ${GOOGLE_CLIENT_SECRET:dummy}
            client-name: Google
            redirect-uri: ${BASEURL:http://localhost:8080}/login/oauth2/code/google
            authorization-grant-type: authorization_code
            scope:
              - email
              - profile

          kakao:
            client-id: ${KAKAO_CLIENT_ID:dummy}
            client-secret: ${KAKAO_CLIENT_SECRET:dummy}
            client-name: Kakao
            client-authentication-method: client_secret_post
            redirect-uri: ${BASEURL:http://localhost:8080}/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            scope:
              - account_email
              - profile_nickname
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub

          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id


closet:
  storage:
    type: ${STORAGE_TYPE:s3}
    local:
      root-path: ${STORAGE_LOCAL_ROOT_PATH:storage}
    s3:
      access-key: ${S3_ACCESS_KEY:dummy_key}
      secret-key: ${S3_SECRET_KEY:dummy_key}
      region: ap-northeast-2
      bucket: ${S3_BUCKET:dummy_bucket}
      presigned-url-expiration: ${S3_PRESIGNED_URL_EXPIRATION:600} # (기본값: 10분)
  admin:
    username: ${ADMIN_USERNAME:admin}
    email: ${ADMIN_EMAIL:admin@admin.com}
    password: ${ADMIN_PASSWORD:admin123}
  weather:
    api:
      base-url: http://apis.data.go.kr/1360000/VilageFcstInfoService_2.0
      service-key: ${KMA_SERVICE_KEY:dummyKey}
      timeout: 10000
      data-type: JSON
  base_url:
    redirect: ${DEPLOY_URL:http://localhost:8080}

logging:
  level:
    root: info
    org.hibernate.sql: info
    org.hibernate.type: info